

CREATE TABLE PRODUCTS(
   ID INT NOT NULL,
   CATEGORY   INT        NOT NULL,
   PRICE   DECIMAL (18, 2),       
   DESCRIPTION VARCHAR (20)     NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER(
   ID INT NOT NULL,
   NAME   VARCHAR (20)        NOT NULL,
   EMAIL   VARCHAR (20) NOT NULL,       
   PRIMARY KEY (ID)
);
CREATE TABLE CUSTOMERORDER(
   ID INT NOT NULL,
   CUSTOMERID INT NOT NULL,
   ORDERDATE    DATE NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE PURCHASE(
   ID INT NOT NULL,
   PRODUCTID    INT NOT NULL,
   ORDERID    INT NOT NULL,
   PRICE   DECIMAL (18, 2),       
   DESCRIPTION VARCHAR (20) NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
   FOREIGN KEY (ORDERID) REFERENCES CUSTOMERORDER(ID)
);

