

CREATE TABLE PRODUCTS(
   ID INT NOT NULL,
   CATEGORY   INT        NOT NULL,
   PRICE   DECIMAL (18, 2),       
   DESCRIPTION VARCHAR (100)     NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER(
   ID INT NOT NULL,
   NAME   VARCHAR (20)        NOT NULL,
   PASSWORD   VARCHAR (20)        NOT NULL,
   EMAIL   VARCHAR (20) NOT NULL,       
   PRIMARY KEY (ID)
);
CREATE TABLE CUSTOMERORDER(
   ID INT NOT NULL,
   CUSTOMERID INT NOT NULL,
   ORDERDATE    DATE NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE PURCHASE(
   ID INT NOT NULL,
   PRODUCTID    INT NOT NULL,
   ORDERID    INT NOT NULL,
   PRICE   DECIMAL (18, 2),       
   DESCRIPTION VARCHAR (20) NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
   FOREIGN KEY (ORDERID) REFERENCES CUSTOMERORDER(ID)
);

/*--------------------------------------Products------------------------------*/
/*TVS*/
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (0, 0, 419, 'LG 50UK6470PLC 50 Smart 4K Ultra HD HDR LED TV - LG');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (1, 0, 219, 'LG 32LK6100 32" Smart HDR LED TV ');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (2, 0, 399, 'TOSHIBA 55U7863DB 55" Smart 4K Ultra HD HDR LED TV');
/*LAPTOPS*/
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (3, 1, 399, 'LENOVO IdeaPad 330S-14IKB 14" Intel® Core™ i5 Laptop - 256 GB SSD, Blue');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (4, 1, 1199, 'LG GRAM i14Z980 14" Intel® Core™ i5 Laptop - 256 GB SSD, Silver');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (5, 1, 579, 'HP 14-ck0599sa 14" Intel® Core™ i7 Laptop - 256 GB SSD, Gold');
/*CONSOLE*/
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (6, 2, 299, 'NINTENDO Switch Neon Red & Mario Kart 8 Deluxe Bundle');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (7, 2, 219, 'MICROSOFT Xbox One S, Fallout 76, Project Cars 2 & Tekken 7 Bundle ');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (8, 2, 249, 'SONY PlayStation 4 with FIFA 19 - 500 GB');
/*CAMERA*/
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (9, 3, 199, 'o	CANON PowerShot SX540 HS Bridge Camera - Black');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (10, 3, 69, 'o	INSTAX mini 9 Instant Camera - Ice Blue ');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (11, 3, 529, 'o	CANON PowerShot G7 X Mark II High Performance Compact Camera - Black ');
/*HEADPHONES*/
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (12, 4, 159, 'APPLE AirPods Wireless Bluetooth Headphones - White');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (13, 4, 299, 'SONY WH-1000XM3 Wireless Bluetooth Noise-Cancelling Headphones - Black ');
INSERT INTO PRODUCTS (ID, CATEGORY, PRICE, DESCRIPTION) VALUES (14, 4, 29, 'JBL T460BT Wireless Bluetooth Headphones - Black');
/*----------------------------------------------------------------------------*/
/*--------------------------------------CUSTOMERS------------------------------*/
INSERT INTO Customer (ID, NAME, PASSWORD, EMAIL) VALUES (0, 'Jillian Billian', 'UnsecurePassword', 'jillianbillian@g.com');
INSERT INTO Customer (ID, NAME, PASSWORD, EMAIL) VALUES (1, 'Joe Baggins', 'UnsecurePassword2', 'joebaggins@g.com');
INSERT INTO Customer (ID, NAME, PASSWORD, EMAIL) VALUES (2, 'Timmy Tommy', 'UnsecurePassword', 'timmytommy@g.com');
INSERT INTO Customer (ID, NAME, PASSWORD, EMAIL) VALUES (3, 'Dogs of War', 'UnsecurePassword', 'dogsofwar@g.com');


